### ISSUE TITLE
你好， 你的机型是fl5900u i7 7500u的吗？

### ISSUE THREAD

**Issue by mokeeqian** [AndromedaX7/MacEFIPartition#1]
我的和你机型一样， 7500u的，可以直接用你的efi吗

**Comment by AndromedaX7** [comment]
我不知道7500u行不行，如果你觉得可以直接拿走



在 2020-07-01 11:29:38，"Cony Qian" <notifications@github.com> 写道：

我的和你机型一样， 7500u的，可以直接用你的efi吗
